"""Tests that PR description is auto-built from round summaries at teardown.

Regression prevention: pr_description was removed from RoundsMetadata.
The description must be built from rounds[], not from a freeform field.
"""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from lifecycle.teardown import _run_teardown
from utils.models import RunContext


def _make_run() -> RunContext:
    return RunContext(
        run_id="test-run",
        agent_role="worker",
        branch_name="autofyn/test-branch",
        base_branch="main",
        duration_minutes=60,
        github_repo="owner/repo",
        total_cost=0.0,
        total_input_tokens=0,
        total_output_tokens=0,
        cache_creation_input_tokens=0,
        cache_read_input_tokens=0,
    )


class TestPrDescriptionFromRounds:
    """PR description must be auto-built from round summaries."""

    @pytest.mark.asyncio
    async def test_description_contains_round_summaries(self) -> None:
        sandbox = MagicMock()
        sandbox.repo.teardown = AsyncMock(
            return_value=MagicMock(
                auto_committed=False, commits_ahead=1,
                pushed=True, push_error=None,
                pr_url="https://github.com/owner/repo/pull/1",
                pr_error=None, diff_stats=[],
            )
        )
        metadata_store = MagicMock()
        metadata_store.load = AsyncMock(return_value=MagicMock(
            pr_title="Fix auth",
            rounds=[
                MagicMock(n=1, summary="Map attack surface"),
                MagicMock(n=2, summary="Exploit login bypass"),
                MagicMock(n=3, summary="Chain SSRF to RCE"),
            ],
        ))

        with patch("lifecycle.teardown.log_audit", new_callable=AsyncMock):
            await _run_teardown(sandbox, _make_run(), metadata_store, 60)

        call_kwargs = sandbox.repo.teardown.call_args.kwargs
        desc = call_kwargs["pr_description"]
        assert "**Round 1:** Map attack surface" in desc
        assert "**Round 2:** Exploit login bypass" in desc
        assert "**Round 3:** Chain SSRF to RCE" in desc
        assert "Generated by AutoFyn" in desc

    @pytest.mark.asyncio
    async def test_no_rounds_shows_fallback(self) -> None:
        sandbox = MagicMock()
        sandbox.repo.teardown = AsyncMock(
            return_value=MagicMock(
                auto_committed=False, commits_ahead=1,
                pushed=True, push_error=None,
                pr_url=None, pr_error=None, diff_stats=[],
            )
        )
        metadata_store = MagicMock()
        metadata_store.load = AsyncMock(return_value=MagicMock(
            pr_title="Test",
            rounds=[],
        ))

        with patch("lifecycle.teardown.log_audit", new_callable=AsyncMock):
            await _run_teardown(sandbox, _make_run(), metadata_store, 60)

        call_kwargs = sandbox.repo.teardown.call_args.kwargs
        assert "No rounds recorded." in call_kwargs["pr_description"]

    @pytest.mark.asyncio
    async def test_rounds_metadata_has_no_pr_description_field(self) -> None:
        from utils.models import RoundsMetadata

        assert not hasattr(RoundsMetadata(), "pr_description")
