"""Git operations: branch creation, pushing, and PR creation.

Handles the case where /workspace is a git submodule (the .git file
points outside the container). On first use we clone from the remote
into a working directory so branches share history with the remote.
"""

import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ALLOWED_REPO = os.environ.get("GITHUB_REPO", "")
_WORK_DIR = "/home/agentuser/repo"
_initialized = False


def _run(args: list[str], cwd: str | None = None, timeout: int = 120) -> str:
    """Run a command and return stdout. Raises on failure."""
    result = subprocess.run(
        args,
        cwd=cwd or _WORK_DIR,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise RuntimeError(f"{' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout.strip()


def _run_git(args: list[str], cwd: str | None = None) -> str:
    return _run(["git"] + args, cwd=cwd)


def _run_gh(args: list[str], cwd: str | None = None) -> str:
    return _run(["gh"] + args, cwd=cwd, timeout=120)


def _ensure_repo() -> None:
    """Ensure we have a proper clone of the repo with shared history.

    We clone from the remote into /home/agentuser/repo/ on first use.
    This avoids the submodule .git issue and ensures branches share
    history with the remote (required for PRs).
    """
    global _initialized
    if _initialized:
        return

    token = os.environ.get("GIT_TOKEN", "")
    if not token or not ALLOWED_REPO:
        raise RuntimeError("GIT_TOKEN and GITHUB_REPO must be set")

    repo_dir = Path(_WORK_DIR)
    remote_url = f"https://x-access-token:{token}@github.com/{ALLOWED_REPO}.git"

    if repo_dir.exists() and (repo_dir / ".git").is_dir():
        # Already cloned — just update remote URL and fetch
        print("[git] Using existing clone, updating remote")
        try:
            _run_git(["remote", "set-url", "origin", remote_url])
            _run_git(["fetch", "origin"])
        except RuntimeError as e:
            print(f"[git] Warning: fetch failed: {e}")
    else:
        # Fresh clone
        print(f"[git] Cloning {ALLOWED_REPO} into {_WORK_DIR}...")
        if repo_dir.exists():
            shutil.rmtree(repo_dir)
        _run(
            ["git", "clone", "--depth", "50", "--no-single-branch", remote_url, _WORK_DIR],
            cwd="/home/agentuser",
            timeout=300,
        )
        print("[git] Clone complete")

    # Copy workspace files that aren't in the repo yet (like self-improve/)
    # The agent works in the cloned repo but can reference /workspace for reading
    _initialized = True


def setup_git_auth() -> None:
    """Initialize the repo clone and configure auth."""
    # Ensure GH_TOKEN is set for gh CLI (mirrors GIT_TOKEN from env_file)
    token = os.environ.get("GIT_TOKEN", "")
    if token and not os.environ.get("GH_TOKEN"):
        os.environ["GH_TOKEN"] = token
    _ensure_repo()


def get_branch_name() -> str:
    """Generate a unique branch name for this run."""
    import uuid
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    short_id = uuid.uuid4().hex[:6]
    return f"improvements-round-{date_str}-{short_id}"


def create_branch(branch_name: str, base_branch: str = "main") -> str:
    """Create and checkout a new branch from the specified base branch."""
    _ensure_repo()
    try:
        _run_git(["fetch", "origin", base_branch])
        _run_git(["checkout", "-B", base_branch, f"origin/{base_branch}"])
    except RuntimeError:
        try:
            _run_git(["checkout", base_branch])
        except RuntimeError:
            print(f"[git] Warning: could not checkout {base_branch}, using current HEAD")

    _run_git(["checkout", "-b", branch_name])
    print(f"[git] Created branch: {branch_name} (from {base_branch})")
    return branch_name


def ensure_staging_branch() -> None:
    """Verify staging branch exists on remote."""
    _ensure_repo()
    try:
        _run_git(["ls-remote", "--exit-code", "--heads", "origin", "staging"])
    except RuntimeError:
        print("[git] Warning: staging branch not found on remote")


def push_branch(branch_name: str) -> None:
    """Push the current branch to origin."""
    _run_git(["push", "-u", "origin", branch_name])


def create_pr(branch_name: str, run_id: str) -> str:
    """Create a PR from the branch to staging. Returns the PR URL."""
    title = f"[Self-Improve] {branch_name}"
    body = (
        "## Self-Improvement Run\n\n"
        f"**Branch:** `{branch_name}`\n"
        f"**Run ID:** `{run_id}`\n\n"
        "This PR was created by the SignalPilot self-improvement agent.\n"
        "Review all changes carefully before merging to staging.\n\n"
        "---\n"
        "*Generated by SignalPilot Self-Improve Framework*"
    )

    url = _run_gh([
        "pr", "create",
        "--base", "staging",
        "--head", branch_name,
        "--title", title,
        "--body", body,
    ])
    return url


def has_changes() -> bool:
    """Check if there are any uncommitted or staged changes."""
    _ensure_repo()
    status = _run_git(["status", "--porcelain"])
    return bool(status.strip())


def get_current_branch() -> str:
    """Get the current branch name."""
    _ensure_repo()
    return _run_git(["branch", "--show-current"])


def get_work_dir() -> str:
    """Return the working directory where the agent should operate."""
    _ensure_repo()
    return _WORK_DIR
