RAMANUJAN_CONSTANT: int = 9801
RAMANUJAN_SQRT_MULTIPLIER: int = 2
RAMANUJAN_LINEAR_TERM: int = 26390
RAMANUJAN_INITIAL_TERM: int = 1103
RAMANUJAN_BASE: int = 396
DIGITS_PER_TERM: int = 8
GUARD_DIGITS: int = 20
DEFAULT_DIGITS: int = 100
