"""API key authentication for the dashboard.

The key lives at /data/api.key (Docker volume), generated by
entrypoint.sh on first boot. Same pattern as master.key for Fernet.

All endpoints authenticate via the X-API-Key header only. The SSE
endpoints previously accepted ?api_key= for browser EventSource
compatibility, but the Next.js proxy now attaches the header server-side,
so query-param auth is no longer needed and has been removed.
"""

import hmac
from pathlib import Path

from fastapi import HTTPException, Security
from fastapi.security import APIKeyHeader

from backend.constants import API_KEY_PATH

_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _load_api_key() -> str:
    """Read the API key from the volume file. Fails fast if missing."""
    p = Path(API_KEY_PATH)
    if not p.exists():
        raise RuntimeError(f"{API_KEY_PATH} not found — entrypoint.sh must generate it")
    return p.read_text().strip()


_api_key = _load_api_key()


def _check(key: str | None) -> None:
    """Raise 401 if the key is missing or wrong."""
    if not key or not hmac.compare_digest(key, _api_key):
        raise HTTPException(status_code=401, detail="Invalid or missing API key")


async def verify_api_key(api_key: str | None = Security(_api_key_header)) -> None:
    """FastAPI dependency — check X-API-Key header."""
    _check(api_key)
