"""Run teardown — finalize a completed run.

After the round loop returns, teardown makes one sandbox call to
`/repo/teardown` which performs commit-leftovers → push → PR →
diff-stats in a single round-trip, then writes the final row to
the runs table.

PR creation is skipped when status == "killed" (sandbox may be gone).
"""

import logging

from db.constants import (
    RUN_STATUS_COMPLETED,
    RUN_STATUS_COMPLETED_NO_CHANGES,
    RUN_STATUS_KILLED,
)
from memory.metadata import MetadataStore
from sandbox_client.client import SandboxClient
from utils import db
from utils.db_logging import log_audit
from utils.constants import RUN_STATE_PATH
from utils.models import RunContext, TeardownResult

log = logging.getLogger("lifecycle.teardown")


async def finalize_run(
    sandbox: SandboxClient,
    run: RunContext,
    metadata_store: MetadataStore,
    status: str,
) -> str | None:
    """Commit residual work, push, open PR, capture diff, finalize DB.

    Returns the PR URL or None if no PR was created.
    """
    pr_url: str | None = None
    resolved_status = status
    diff_stats: list[dict] | None = None

    if status != RUN_STATUS_KILLED and not run.skip_pr:
        result = await _run_teardown(sandbox, run, metadata_store)
        if result is not None:
            pr_url = result.pr_url
            diff_stats = result.diff_stats
            await _log_teardown_outcome(run, result)
            if result.commits_ahead == 0 and status == RUN_STATUS_COMPLETED:
                resolved_status = RUN_STATUS_COMPLETED_NO_CHANGES

    await db.finish_run(
        run.run_id,
        resolved_status,
        pr_url,
        run.total_cost,
        run.total_input_tokens,
        run.total_output_tokens,
        None,
        None,
        diff_stats,
        run.cache_creation_input_tokens,
        run.cache_read_input_tokens,
    )
    log.info(
        "Run complete: status=%s cost=$%.2f pr=%s",
        resolved_status, run.total_cost, pr_url or "-",
    )
    return pr_url


# ── Teardown call ────────────────────────────────────────────────────


async def _run_teardown(
    sandbox: SandboxClient,
    run: RunContext,
    metadata_store: MetadataStore,
) -> TeardownResult | None:
    """Call /repo/teardown with the PR title/description from metadata."""
    metadata = await metadata_store.load()
    title = metadata.pr_title or f"[AutoFyn] {run.branch_name}"
    round_lines = [
        f"- **Round {r.n}:** {r.summary}" for r in metadata.rounds
    ]
    body = "\n".join(round_lines) if round_lines else "No rounds recorded."
    run_state = await sandbox.file_system.read(RUN_STATE_PATH)
    run_state_section = (
        f"\n\n<details><summary>Run State</summary>\n\n{run_state}\n</details>"
        if run_state else ""
    )
    footer = (
        f"\n\n---\n**Branch:** `{run.branch_name}` · "
        f"**Run:** `{run.run_id}` · *Generated by AutoFyn*"
    )
    description = body + run_state_section + footer

    try:
        return await sandbox.repo.teardown(
            pr_title=title,
            pr_description=description,
            base=run.base_branch,
        )
    except Exception as exc:
        log.error("Teardown call failed: %s", exc, exc_info=True)
        await log_audit(run.run_id, "teardown_failed", {"error": str(exc)})
        return None


async def _log_teardown_outcome(run: RunContext, result: TeardownResult) -> None:
    """Emit audit events for each stage of the teardown result."""
    if result.auto_committed:
        await log_audit(run.run_id, "auto_commit", {
            "reason": "uncommitted changes at teardown",
        })

    if result.commits_ahead == 0:
        log.info("No commits ahead of %s — nothing to PR", run.base_branch)
        await log_audit(run.run_id, "no_changes", {
            "base_branch": run.base_branch,
        })
        return

    if not result.pushed:
        log.warning("Teardown push failed: %s", result.push_error)
        await log_audit(run.run_id, "push_failed", {
            "phase": "teardown",
            "error": result.push_error,
        })
        return

    if result.pr_error:
        log.error("PR creation failed: %s", result.pr_error)
        await log_audit(run.run_id, "pr_failed", {"error": result.pr_error})
        return

    if result.pr_url:
        log.info("PR created: %s", result.pr_url)
        await log_audit(run.run_id, "pr_created", {"url": result.pr_url})
