"""Run teardown — finalize a completed run.

After the round loop returns, teardown:

    1. Ensures a final commit if anything is still uncommitted.
    2. Pushes once more (safe no-op if already pushed).
    3. Reads rounds.json for the PR title + description.
    4. Creates (or edits) the pull request via sandbox /repo/pr.
    5. Captures diff stats.
    6. Writes the final row to the runs table.

PR creation is skipped when status == "killed" (sandbox may be gone) or
when the branch has no commits ahead of base (no-op run).
"""

import logging

from memory.metadata import MetadataStore
from sandbox_client.client import SandboxClient
from utils import db
from utils.models import RunContext

log = logging.getLogger("lifecycle.teardown")


async def finalize_run(
    sandbox: SandboxClient,
    run: RunContext,
    metadata_store: MetadataStore,
    status: str,
    exec_timeout: int,
) -> str | None:
    """Commit residual work, push, open PR, capture diff, finalize DB.

    Returns the PR URL or None if no PR was created.
    """
    pr_url: str | None = None
    resolved_status = status

    if status != "killed":
        pr_url = await _open_pr(
            sandbox, run, metadata_store, exec_timeout,
        )
        if pr_url is None and status == "completed":
            resolved_status = "completed_no_changes"

    diff_stats = await _capture_diff(sandbox, run, exec_timeout)

    await db.finish_run(
        run.run_id,
        resolved_status,
        pr_url,
        run.total_cost,
        run.total_input_tokens,
        run.total_output_tokens,
        None,
        None,
        diff_stats,
        run.cache_creation_input_tokens,
        run.cache_read_input_tokens,
    )
    log.info(
        "Run complete: status=%s cost=$%.2f pr=%s",
        resolved_status, run.total_cost, pr_url or "-",
    )
    return pr_url


# ── PR creation ──────────────────────────────────────────────────────


async def _open_pr(
    sandbox: SandboxClient,
    run: RunContext,
    metadata_store: MetadataStore,
    exec_timeout: int,
) -> str | None:
    """Commit leftovers, push, and create/update the PR. None if nothing to ship."""
    try:
        current = await sandbox.repo.current_branch(exec_timeout)
        if current != run.branch_name:
            log.warning(
                "Not on expected branch %s (on %s), skipping push/PR",
                run.branch_name, current,
            )
            return None

        if await sandbox.repo.has_changes(exec_timeout):
            log.info("Auto-committing leftover changes before teardown PR")
            committed = await sandbox.repo.commit(
                "Auto-commit: save uncommitted work at session end",
                exec_timeout,
            )
            if committed:
                await db.log_audit(run.run_id, "auto_commit", {
                    "reason": "uncommitted changes at teardown",
                })

        ahead = await sandbox.repo.commits_ahead(run.base_branch, exec_timeout)
        if ahead == 0:
            log.info("No commits ahead of %s — nothing to PR", run.base_branch)
            await db.log_audit(run.run_id, "no_changes", {
                "base_branch": run.base_branch,
            })
            return None

        try:
            await sandbox.repo.push(exec_timeout)
        except Exception as exc:
            log.warning("Teardown push failed: %s", exc)
            return None

        metadata = await metadata_store.load()
        title = metadata.pr_title or f"[AutoFyn] {run.branch_name}"
        footer = (
            f"\n\n---\n**Branch:** `{run.branch_name}` · "
            f"**Run:** `{run.run_id}` · *Generated by AutoFyn*"
        )
        description = (
            metadata.pr_description + footer
            if metadata.pr_description
            else footer.lstrip("\n")
        )

        url = await sandbox.repo.create_or_update_pr(
            title, description, run.base_branch, exec_timeout,
        )
        log.info("PR created: %s", url)
        await db.log_audit(run.run_id, "pr_created", {"url": url})
        return url
    except Exception as exc:
        log.error("PR creation failed: %s", exc)
        await db.log_audit(run.run_id, "pr_failed", {"error": str(exc)})
        return None


# ── Diff capture ─────────────────────────────────────────────────────


async def _capture_diff(
    sandbox: SandboxClient,
    run: RunContext,
    exec_timeout: int,
) -> list[dict] | None:
    """Best-effort diff stats for the runs table."""
    try:
        return await sandbox.repo.branch_diff(run.base_branch, exec_timeout)
    except Exception as exc:
        log.warning("Failed to capture diff stats: %s", exc)
        return None
