#!/usr/bin/env bash
set -euo pipefail
cd "$HOME/.autofyn"
export AGENT_INTERNAL_SECRET="${AGENT_INTERNAL_SECRET:-$(openssl rand -hex 32)}"
export SANDBOX_INTERNAL_SECRET="${SANDBOX_INTERNAL_SECRET:-$(openssl rand -hex 32)}"
export CONNECTOR_SECRET="${CONNECTOR_SECRET:-$(openssl rand -hex 32)}"
export AF_SANDBOX_PORT="${AF_SANDBOX_PORT:-8923}"
PYTHON_VERSION=3.12
NODE_VERSION=22
UV_VERSION=0.11
GVISOR_VERSION=20260323.0
DOCKER_CLI_VERSION=27.5.1
POSTGRES_VERSION=16
UBUNTU_VERSION=22.04
docker compose build \
    --build-arg PYTHON_VERSION="$PYTHON_VERSION" \
    --build-arg NODE_VERSION="$NODE_VERSION" \
    --build-arg UV_VERSION="$UV_VERSION" \
    --build-arg GVISOR_VERSION="$GVISOR_VERSION" \
    --build-arg DOCKER_CLI_VERSION="$DOCKER_CLI_VERSION" \
    --build-arg POSTGRES_VERSION="$POSTGRES_VERSION" \
    --build-arg UBUNTU_VERSION="$UBUNTU_VERSION"
