RAMANUJAN_SQRT_FACTOR: int = 2
RAMANUJAN_PREFACTOR_DENOM: int = 9801
RAMANUJAN_LINEAR_BASE: int = 1103
RAMANUJAN_LINEAR_STEP: int = 26390
RAMANUJAN_BASE: int = 396
RAMANUJAN_DIGITS_PER_TERM: int = 8
GUARD_DIGITS: int = 15
DEFAULT_DIGITS: int = 100
