DEFAULT_DIGITS: int = 100
RAMANUJAN_COEFFICIENT_NUMERATOR: int = 2
RAMANUJAN_COEFFICIENT_DENOMINATOR: int = 9801
RAMANUJAN_LINEAR_TERM: int = 26390
RAMANUJAN_CONSTANT_TERM: int = 1103
RAMANUJAN_BASE: int = 396
