"""Connector constants — all magic values for the connector package."""

CONNECTOR_DEFAULT_PORT: int = 9400
CONNECTOR_BIND_HOST: str = "127.0.0.1"

CONNECTOR_SECRET_HEADER: str = "X-Connector-Secret"
SANDBOX_SECRET_HEADER: str = "X-Internal-Secret"

TUNNEL_HEALTH_PROBE_INTERVAL_SEC: int = 30
HEARTBEAT_INTERVAL_SEC: int = 60

SHUTDOWN_TIMEOUT_SEC: int = 60

SSH_CONNECT_TIMEOUT_SEC: int = 30
SSH_KEEPALIVE_INTERVAL_SEC: int = 15

RING_BUFFER_MAX_LINES: int = 100

AF_QUEUED_MARKER: str = "AF_QUEUED"
AF_READY_MARKER: str = "AF_READY"

DEFAULT_SECRET_DIR: str = "~/.autofyn/secrets"
